{
  "hash": "9425f9b5f680db8343400bbee7ff4f64",
  "result": {
    "markdown": "---\ntitle: Lab 12\ndate: 07/17/2023\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.2     ✔ readr     2.1.4\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ ggplot2   3.4.2     ✔ tibble    3.2.1\n✔ lubridate 1.9.2     ✔ tidyr     1.3.0\n✔ purrr     1.0.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\nsafety <- read.csv(\"https://raw.githubusercontent.com/IAA-Faculty/statistical_foundations/master/safety.csv\")\n```\n:::\n\n\n# 1\n\n## a\n\n-   `Unsafe` is ordinal\n-   `Type` is nominal\n-   `Region` is ordinal\n-   `Weight` is ordinal\n-   `Size` is ordinal\n\n## b\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(safety$Region, safety$Unsafe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           \n             0  1\n  Asia      20 15\n  N America 46 15\n```\n:::\n\n```{.r .cell-code}\nggplot(safety) +\n    geom_bar(aes(x = Region, fill = factor(Unsafe)))\n```\n\n::: {.cell-output-display}\n![](lab_12_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n-   Percentage of cars classified as unsafe in the Asia region is 42.9 percent\n-   Percentage of cars classified as safe in the North America region is 75.4 percent\n-   Appropriate test to use is Mantel-Haenszel\n    -   $H_0:$ No linear association, $H_a:$ Linear association exists\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vcdExtra)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: vcd\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: grid\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: gnm\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'vcdExtra'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:dplyr':\n\n    summarise\n```\n:::\n\n```{.r .cell-code}\nlibrary(DescTools)\n\nCMHtest(table(safety$Region, safety$Unsafe))$table[1, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Chisq         Df       Prob \n3.41813924 1.00000000 0.06448366 \n```\n:::\n\n```{.r .cell-code}\nOddsRatio(table(safety$Region, safety$Unsafe))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4347826\n```\n:::\n\n```{.r .cell-code}\ntable(safety$Region, safety$Unsafe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           \n             0  1\n  Asia      20 15\n  N America 46 15\n```\n:::\n:::\n\n\n-   At an $\\alpha$ level of 0.05, we do not reject the null hypothesis that there is no linear association between `Region` and `Safety`\n-   There are 0.435 times the odds to be safe if it's in the Asia region\n\n## c\n\nAppropriate test is Mantel-Haenszel\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCMHtest(table(safety$Size, safety$Unsafe))$table[1, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       Chisq           Df         Prob \n2.770978e+01 1.000000e+00 1.409484e-07 \n```\n:::\n:::\n\n\n-   We reject the null hypothesis that there is no linear association between the two variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(\n    x = as.numeric(ordered(safety$Size)), \n    y = as.numeric(ordered(safety$Unsafe)), \n    method = \"spearman\"\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in cor.test.default(x = as.numeric(ordered(safety$Size)), y =\nas.numeric(ordered(safety$Unsafe)), : Cannot compute exact p-value with ties\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tSpearman's rank correlation rho\n\ndata:  as.numeric(ordered(safety$Size)) and as.numeric(ordered(safety$Unsafe))\nS = 227423, p-value = 1.136e-08\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n       rho \n-0.5424769 \n```\n:::\n:::\n\n\n-   It's not too strong at $\\rho = -0.542$",
    "supporting": [
      "lab_12_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}