project:
  type: website

execute: 
  freeze: auto

website:
  title: "Yang MSA"
  navbar:
    right:
      - notes/index.qmd
      - blog/index.qmd
      - icon: github
        href: https://github.com/yangrchen
  favicon: favicon.ico
format:
  html:
    theme: cosmo
    css: styles.css
