---
title: "First Weeks: Initial Thoughts"
date: 07/11/2023
---
<!-- Could add in more specific stories in general -->

How would I describe the Institute for Advanced Analytics? It's fast, it's *scary*, and it's absolutely thrilling.

Coming in as a Master's student, I'm not sure I knew what to expect entirely. Just a few months ago I had a vastly different vision of trekking out to California to be a full-time art student. But becoming a data science professional?

It seemed unlikely.

To be honest, I often feel like formal education has been a barrier rather than a support for practical learning. I'm sure many students have shared a similar opinion.

Here, "education" takes on a vastly different meaning than compared to an undergraduate program. Team work is crucial at the Institute and your success in any assignment, project, and interaction is defined by the success of your team. From day one, it was crystal clear that the faculty were incredibly passionate in both data science and teaching. Genuine smiles, genuine knowledge, genuine experience--it's hard to beat.

I love the other students as well even if we might not know each other at all. Everybody brings in a wildly different background. We're a medley of primary school teachers, engineers, therapists, PhD students and more coming together to bash our brains and personalities together. Despite the differences between all of us, we share a similar drive to solve difficult problems and be the best data professionals we can be. We're not all friends and we might not have to be, but we all stand to learn something new every day from each other.

I realize before coming here, I tended to avoid teamwork when I could. Now I actually look forward to it. I find myself using a more analytical mindset to validate approaches, project scope, and data design. Now that I'm working for longer periods of time with a group, I'm appreciating the push-and-pull dynamic that is produced when we are discussing how to move a project forward. It's not so simple as a "hero" figure pulling ahead to complete the assignment for everyone. Instead, each of us is learning to work with the friction or flow that is produced when trying to manage everyone's expectations, emotions, work methods, and energies. There's an ongoing process that we all have a part to play in; we can't just hear, we need to listen to the thoughts and experiences of our teammates.

You also can't beat the adrenaline rush that comes when we all figured out or won at something.

If there's one key takeaway I have from the Institute it's that data science can be a new art for me. I often find myself reflecting on what data science means to me. I've heard it being compared to art in many ways, but I never felt a coherent connection between the two disciplines until recently. I don't think typing characters on a keyboard elicits the same feeling of dexterity as putting pencil to paper with broad, sweeping strokes. However, data science does have this wonderful ebb and flow between unstructured data and diverse analytics methods to understand the data. No one method is completely correct, but some can resolve the large shapes and lines in the dataset to a coherent story which can be important to me or any one who views the story. I absolutely believe this notion of data agrees with how I feel towards making art. 