{
  "hash": "4a35128ea9ecac384295268bc5b8447b",
  "result": {
    "markdown": "# 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(AppliedPredictiveModeling)\ndata(FuelEconomy)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(cars2010[, c(\"EngDispl\", \"NumCyl\", \"ExhaustValvesPerCyl\", \"VarValveTiming\", \"FE\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                       EngDispl       NumCyl ExhaustValvesPerCyl VarValveTiming\nEngDispl             1.00000000  0.906260027          -0.4784380   -0.068256030\nNumCyl               0.90626003  1.000000000          -0.3398518    0.005399291\nExhaustValvesPerCyl -0.47843804 -0.339851831           1.0000000    0.279339052\nVarValveTiming      -0.06825603  0.005399291           0.2793391    1.000000000\nFE                  -0.78739383 -0.740217981           0.3356529    0.124952779\n                            FE\nEngDispl            -0.7873938\nNumCyl              -0.7402180\nExhaustValvesPerCyl  0.3356529\nVarValveTiming       0.1249528\nFE                   1.0000000\n```\n:::\n\n```{.r .cell-code}\npairs(cars2010[, c(\"EngDispl\", \"NumCyl\", \"ExhaustValvesPerCyl\", \"VarValveTiming\", \"FE\")])\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\nengdispl_lm <- lm(FE ~ EngDispl, data = cars2010)\npar(nfrow = c(2, 2))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in par(nfrow = c(2, 2)): \"nfrow\" is not a graphical parameter\n```\n:::\n\n```{.r .cell-code}\nplot(engdispl_lm)\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-2-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-2-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-2-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-2-5.png){width=672}\n:::\n\n```{.r .cell-code}\nsummary(engdispl_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = FE ~ EngDispl, data = cars2010)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-14.486  -3.192  -0.365   2.671  27.215 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  50.5632     0.3985  126.89   <2e-16 ***\nEngDispl     -4.5209     0.1065  -42.46   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.624 on 1105 degrees of freedom\nMultiple R-squared:   0.62,\tAdjusted R-squared:  0.6196 \nF-statistic:  1803 on 1 and 1105 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n-   Highest correlation with `FE` is `EnglDispl`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(cars2010$FE, cars2010$EngDispl)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  cars2010$FE and cars2010$EngDispl\nt = -42.46, df = 1105, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.8087913 -0.7639144\nsample estimates:\n       cor \n-0.7873938 \n```\n:::\n:::\n\n\n-   P-value is significant at a 0.05 level and we have evidence that the correlation coefficient is not equal to 0\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(cars2010[, c(\"EngDispl\", \"NumCyl\", \"ExhaustValvesPerCyl\", \"VarValveTiming\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                       EngDispl       NumCyl ExhaustValvesPerCyl VarValveTiming\nEngDispl             1.00000000  0.906260027          -0.4784380   -0.068256030\nNumCyl               0.90626003  1.000000000          -0.3398518    0.005399291\nExhaustValvesPerCyl -0.47843804 -0.339851831           1.0000000    0.279339052\nVarValveTiming      -0.06825603  0.005399291           0.2793391    1.000000000\n```\n:::\n:::\n\n\n-   `EnglDispl` and `NumCyl` have a large correlation between one another\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslr <- lm(FE ~ EngDispl, cars2010)\nsummary(slr)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.619989\n```\n:::\n:::\n\n\n-   F-statistic is 1803 with a p-value of 2.2e-16. Overall model is significant\n-   $y = 50.5632 - 4.5209x_1$ \n-   $R^2$ is 0.620 which means that 62% of the variability in `FE` can be explained by `EngDispl` alone\n\n# 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.2     ✔ readr     2.1.4\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ ggplot2   3.4.2     ✔ tibble    3.2.1\n✔ lubridate 1.9.2     ✔ tidyr     1.3.0\n✔ purrr     1.0.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nicecream <- read.csv(\"https://raw.githubusercontent.com/IAA-Faculty/statistical_foundations/master/icecream.csv\", sep = \" \")\nglimpse(icecream)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 50\nColumns: 2\n$ Temperature <int> 65, 87, 78, 68, 98, 86, 62, 86, 71, 85, 78, 90, 63, 80, 80…\n$ Sales       <dbl> 180.25, 218.75, 202.44, 176.50, 212.18, 210.68, 165.30, 22…\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsales_slr <- lm(Sales ~ Temperature, icecream)\npar(mfrow = c(2, 2))\nplot(sales_slr)\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(icecream, aes(x = Temperature, y = Sales)) +\n    geom_point() +\n    stat_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n\n```{.r .cell-code}\nsummary(sales_slr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Sales ~ Temperature, data = icecream)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-21.603  -8.159   1.005   7.212  23.666 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 119.3895    10.1931  11.713 1.12e-15 ***\nTemperature   1.0889     0.1241   8.771 1.54e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.07 on 48 degrees of freedom\nMultiple R-squared:  0.6158,\tAdjusted R-squared:  0.6078 \nF-statistic: 76.94 on 1 and 48 DF,  p-value: 1.543e-11\n```\n:::\n:::\n\n\n-   Residuals seem to be Normally distributed from the QQ-Plot\n-   Error variance is constant and does not show a pattern\n-   Linearity of the mean\n-   Overall F-test is significant so `Temperature` seems to be significant in explaining `Sales`\n-   Parameter estimate for `Temperature` is 1.0889\n\n# 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nminntemp <- read.csv(\"https://raw.githubusercontent.com/IAA-Faculty/statistical_foundations/master/minntemp.csv\", sep = \" \")\nglimpse(minntemp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 795\nColumns: 3\n$ Temp   <dbl> 73.04, 73.04, 73.04, 69.98, 69.08, 69.98, 69.98, 71.96, 75.02, …\n$ TimeSq <int> 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, …\n$ Time   <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, …\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp_slr <- lm(Temp ~ Time, minntemp)\npar(mfrow = c(2, 2))\nplot(temp_slr)\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(minntemp, aes(x = Time, y = Temp)) +\n    geom_point() +\n    stat_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n\n```{.r .cell-code}\nsummary(temp_slr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Temp ~ Time, data = minntemp)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-20.8189  -5.4495  -0.5359   5.1432  21.1455 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 70.755366   0.588230 120.285   <2e-16 ***\nTime         0.002301   0.001280   1.797   0.0727 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.285 on 793 degrees of freedom\nMultiple R-squared:  0.004056,\tAdjusted R-squared:  0.0028 \nF-statistic: 3.229 on 1 and 793 DF,  p-value: 0.07271\n```\n:::\n:::\n\n\n-   No linearity of the mean, seems quadratic\n-   No constant variance\n-   Normally distributed errors\n-   No statistical evidence that `time` is related to `temperature` at a confidence level of 0.05",
    "supporting": [
      "lab_4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}