{
  "hash": "869984e2d60371a11ac4dcadd2d4ef4c",
  "result": {
    "markdown": "::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.2     ✔ readr     2.1.4\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ ggplot2   3.4.2     ✔ tibble    3.2.1\n✔ lubridate 1.9.2     ✔ tidyr     1.3.0\n✔ purrr     1.0.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\nlibrary(UsingR)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: MASS\n\nAttaching package: 'MASS'\n\nThe following object is masked from 'package:dplyr':\n\n    select\n\nLoading required package: HistData\nLoading required package: Hmisc\n\nAttaching package: 'Hmisc'\n\nThe following objects are masked from 'package:dplyr':\n\n    src, summarize\n\nThe following objects are masked from 'package:base':\n\n    format.pval, units\n```\n:::\n\n```{.r .cell-code}\ndata(normtemp)\nglimpse(normtemp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 130\nColumns: 3\n$ temperature <dbl> 96.3, 96.7, 96.9, 97.0, 97.1, 97.1, 97.1, 97.2, 97.3, 97.4…\n$ gender      <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ hr          <int> 70, 71, 74, 80, 73, 75, 82, 64, 69, 70, 68, 72, 78, 70, 75…\n```\n:::\n\n```{.r .cell-code}\n?normtemp\n```\n:::\n\n\n1.  Revisit the NormTemp dataset from Lab 1, where we examined the observed \nmean body temperature (temperature) in comparison to the well-known \n“average” of 98.6\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(normtemp$temperature, mu = 98.6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  normtemp$temperature\nt = -5.4548, df = 129, p-value = 2.411e-07\nalternative hypothesis: true mean is not equal to 98.6\n95 percent confidence interval:\n 98.12200 98.37646\nsample estimates:\nmean of x \n 98.24923 \n```\n:::\n:::\n\n\n-   The p-value is 2.411e-07\n-   The p-value is the probability that we observe our data given that the mean body temperature is 98.6\n-   Given our low p-value at a significance level of $\\alpha = 0.05$ we reject our null hypothesis. We believe the actual mean is significantly different from 98.6\n-   The 95% confidence interval for temperature is [98.12200, 98.37646]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfemales <- normtemp[normtemp$gender == 2, ]\nt.test(females$temperature, mu = 98.6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  females$temperature\nt = -2.2355, df = 64, p-value = 0.02888\nalternative hypothesis: true mean is not equal to 98.6\n95 percent confidence interval:\n 98.20962 98.57807\nsample estimates:\nmean of x \n 98.39385 \n```\n:::\n:::\n\n\n-   Given our p-value $< \\alpha$ our conclusion does not change\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(normtemp, aes(sample = temperature, color = gender)) +\n    stat_qq() +\n    stat_qq_line()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: The following aesthetics were dropped during statistical transformation: colour\nℹ This can happen when ggplot fails to infer the correct grouping structure in\n  the data.\nℹ Did you forget to specify a `group` aesthetic or to convert a numerical\n  variable into a factor?\nThe following aesthetics were dropped during statistical transformation: colour\nℹ This can happen when ggplot fails to infer the correct grouping structure in\n  the data.\nℹ Did you forget to specify a `group` aesthetic or to convert a numerical\n  variable into a factor?\n```\n:::\n\n::: {.cell-output-display}\n![](lab_2_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n-   Approximately Normal\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar.test(temperature ~ gender, data = normtemp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tF test to compare two variances\n\ndata:  temperature by gender\nF = 0.88329, num df = 64, denom df = 64, p-value = 0.6211\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.5387604 1.4481404\nsample estimates:\nratio of variances \n         0.8832897 \n```\n:::\n:::\n\n\n- We believe variances are equal\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(temperature ~ gender, data = normtemp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  temperature by gender\nt = -2.2854, df = 127.51, p-value = 0.02394\nalternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0\n95 percent confidence interval:\n -0.53964856 -0.03881298\nsample estimates:\nmean in group 1 mean in group 2 \n       98.10462        98.39385 \n```\n:::\n:::\n\n\n-   At a significance level of 0.05, we reject our null hypothesis that there is no difference in means between the two genders\n\n1.  The Airline dataset contains information regarding the number of international \nairline travelers (variable air) across different months of the year from \n1949-1960. We are interested in knowing if during this time period there was a\nsignificant difference between air travel in the Summer months of June,\nJuly, and August vs. the remainder of the year? Use a statistical \nhypothesis test (alpha=0.05) to support your answer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(AirPassengers)\nlibrary(tseries)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRegistered S3 method overwritten by 'quantmod':\n  method            from\n  as.zoo.data.frame zoo \n```\n:::\n\n```{.r .cell-code}\nlibrary(forecast)\ncycle(AirPassengers)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec\n1949   1   2   3   4   5   6   7   8   9  10  11  12\n1950   1   2   3   4   5   6   7   8   9  10  11  12\n1951   1   2   3   4   5   6   7   8   9  10  11  12\n1952   1   2   3   4   5   6   7   8   9  10  11  12\n1953   1   2   3   4   5   6   7   8   9  10  11  12\n1954   1   2   3   4   5   6   7   8   9  10  11  12\n1955   1   2   3   4   5   6   7   8   9  10  11  12\n1956   1   2   3   4   5   6   7   8   9  10  11  12\n1957   1   2   3   4   5   6   7   8   9  10  11  12\n1958   1   2   3   4   5   6   7   8   9  10  11  12\n1959   1   2   3   4   5   6   7   8   9  10  11  12\n1960   1   2   3   4   5   6   7   8   9  10  11  12\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nair1 = data.frame(AirPassengers)\nair2 = air1 |> mutate(summer = ifelse(cycle(AirPassengers) %in% 6:8, 1, 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(air2, aes(sample = AirPassengers, color = factor(summer))) +\n    stat_qq() +\n    stat_qq_line()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nDon't know how to automatically pick scale for object of type <ts>. Defaulting\nto continuous.\nDon't know how to automatically pick scale for object of type <ts>. Defaulting\nto continuous.\n```\n:::\n\n::: {.cell-output-display}\n![](lab_2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n-   Normality not met. We will use a nonparametric test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(air2, aes(x = AirPassengers, color = factor(summer))) +\n    geom_density()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nDon't know how to automatically pick scale for object of type <ts>. Defaulting\nto continuous.\n```\n:::\n\n::: {.cell-output-display}\n![](lab_2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n-   After plotting the distributions of both groups, we can see a similar shape but not a similar enough variation between the two groups.\n-   When we are conducting the Wilcoxon test we can't necessarily claim anything about the mean or median but moreso about the distributional dominance\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(AirPassengers ~ summer, data = air2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  AirPassengers by summer\nW = 1346.5, p-value = 0.00588\nalternative hypothesis: true location shift is not equal to 0\n```\n:::\n:::\n\n\n-   At a significance level of 0.05, we reject our null hypothesis that the true location shift is equal to 0",
    "supporting": [
      "lab_2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}