{
  "hash": "2da7ebd4181f35392c512884d9d61b36",
  "result": {
    "markdown": "---\ntitle: Lab 13\ndate: 07/18/2023\n---\n\n\n## a\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nsafety <- read.csv(\"https://raw.githubusercontent.com/IAA-Faculty/statistical_foundations/master/safety.csv\")\n\nsafety <- safety %>%\n    mutate(across(c(Region, Size), as.factor))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- glm(Unsafe ~ Region + Weight + Size, family = binomial(), data = safety)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = Unsafe ~ Region + Weight + Size, family = binomial(), \n    data = safety)\n\nCoefficients:\n                Estimate Std. Error z value Pr(>|z|)   \n(Intercept)       2.7285     1.3949   1.956  0.05046 . \nRegionN America  -0.3775     0.5624  -0.671  0.50203   \nWeight           -0.6678     0.4589  -1.455  0.14559   \nSize2            -2.0200     0.6246  -3.234  0.00122 **\nSize3            -2.6785     0.8810  -3.040  0.00236 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 119.249  on 95  degrees of freedom\nResidual deviance:  84.004  on 91  degrees of freedom\nAIC: 94.004\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n:::\n\n\nSignificant variables are `Size`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survival)\nconcordance(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\nconcordance.lm(object = model)\n\nn= 96 \nConcordance= 0.8482 se= 0.03897\nconcordant discordant     tied.x     tied.y    tied.xy \n      1622        243        115       2273        307 \n```\n:::\n:::\n\n\nModel correctly ranks unsafe cars ahead of safe cars 84.8% of the time.\n\n## b\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- glm(Unsafe ~ Weight + Size, data = safety, family = binomial())\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = Unsafe ~ Weight + Size, family = binomial(), data = safety)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)   \n(Intercept)   2.5272     1.3427   1.882  0.05981 . \nWeight       -0.6686     0.4553  -1.469  0.14195   \nSize2        -2.0142     0.6222  -3.237  0.00121 **\nSize3        -2.7911     0.8666  -3.221  0.00128 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 119.249  on 95  degrees of freedom\nResidual deviance:  84.455  on 92  degrees of freedom\nAIC: 92.455\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- glm(Unsafe ~ Size, data = safety, family = binomial())\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = Unsafe ~ Size, family = binomial(), data = safety)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   0.6506     0.3561   1.827 0.067708 .  \nSize2        -2.2192     0.6070  -3.656 0.000256 ***\nSize3        -3.3586     0.8125  -4.134 3.57e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 119.249  on 95  degrees of freedom\nResidual deviance:  86.629  on 93  degrees of freedom\nAIC: 92.629\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nconcordance(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\nconcordance.lm(object = model3)\n\nn= 96 \nConcordance= 0.8182 se= 0.043\nconcordant discordant     tied.x     tied.y    tied.xy \n      1392        132        456       1539       1041 \n```\n:::\n\n```{.r .cell-code}\nexp(cbind(coef(model3), confint(model3)))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                             2.5 %    97.5 %\n(Intercept) 1.91666667 0.971535104 3.9816962\nSize2       0.10869565 0.030145216 0.3357070\nSize3       0.03478261 0.005058893 0.1414522\n```\n:::\n:::\n\n\nOnly `Size` remained in the model. 0.8182 C-statistic\n\nThe interpretation of the `Size` variable in the model is that Size2 is 0.108 times more likely to be unsafe than compared to Size1. Size3 is 0.03 times more likely to be unsafe than compared to Size1.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}