on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1' # The R version to download (if necessary) and use.

      - name: Install libudunits2-dev
        run: sudo apt-get install -y libudunits2-dev
      - run: sudo apt-get install -y libproj-dev

      - name: Set up renv 
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      
      - name: Set up Jupyter
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
